name: release-tag

on:
  release:
  #types: [published]
  #push

jobs:
  release-image:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_ORG: ${{ github.actor }}
      DOCKER_PACKAGE: pelican-panel
      DOCKER_LATEST: testing
      RUNNER_TOOL_CACHE: /toolcache
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.PASSWORD_DOCKERHUB }}

      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.PASSWORD_GITHUB }}

      - name: Get Meta
        id: meta
        run: |
          echo REPO=$(echo ${{ github.actor }} | awk '{print tolower($0)}') >> $GITHUB_OUTPUT
          #echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_NAME=$(echo ${{ env.DOCKER_PACKAGE }}) >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(git describe --tags --always | sed 's/^v//') >> $GITHUB_OUTPUT            
          echo DATE=$(date) >> $GITHUB_OUTPUT


      - name: Build and push base image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.base
          platforms: |
            linux/386
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.REPO }}/${{ steps.meta.outputs.REPO_NAME }}-base:${{ steps.meta.outputs.REPO_VERSION }}
            ghcr.io/${{ steps.meta.outputs.REPO }}/${{ steps.meta.outputs.REPO_NAME }}-base:${{ env.DOCKER_LATEST }}
          labels: |
            org.opencontainers.image.authors=${{ github.actor }}
            org.opencontainers.image.source=https://github.com/${{ github.actor }}/${{ github.repository }}
            org.opencontainers.image.title=Pelican Panel Base Image    
            org.opencontainers.image.description=Modified Pelican Panel Base Image for Unraid  
            org.opencontainers.image.created=${{ steps.meta.outputs.DATE }}
            org.opencontainers.image.version=${{ steps.meta.outputs.REPO_VERSION }}
          provenance: false


      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
             VERSION=1.0.0-${{ steps.meta.outputs.REPO_VERSION }}
          platforms: |
            linux/386
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
          push: true
          tags: |
            ${{ steps.meta.outputs.REPO }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}
            ${{ steps.meta.outputs.REPO }}/${{ steps.meta.outputs.REPO_NAME }}:${{ env.DOCKER_LATEST }}
            ghcr.io/${{ steps.meta.outputs.REPO }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}
            ghcr.io/${{ steps.meta.outputs.REPO }}/${{ steps.meta.outputs.REPO_NAME }}:${{ env.DOCKER_LATEST }}
          labels: |
            org.opencontainers.image.authors=${{ github.actor }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.title=Pelican Panel
            org.opencontainers.image.description=Modified Pelican Panel for Unraid
            org.opencontainers.image.created=${{ steps.meta.outputs.DATE }}
            org.opencontainers.image.version=${{ steps.meta.outputs.REPO_VERSION }}
          provenance: false
